# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: mongoid_auto_increment 0.1.5 ruby lib

Gem::Specification.new do |s|
  s.name = "mongoid_auto_increment".freeze
  s.version = "0.1.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Peter Savichev (proton)".freeze]
  s.date = "2018-11-07"
  s.description = "Add SQL like auto-incrementing fields to your Mongoid documents.".freeze
  s.email = "psavichev@gmail.com".freeze
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".rspec",
    ".travis.yml",
    "Gemfile",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/mongoid_auto_increment.rb",
    "lib/mongoid_auto_increment/incrementor.rb",
    "mongoid_auto_increment.gemspec",
    "spec/models/book.rb",
    "spec/models/comment.rb",
    "spec/models/ingredient.rb",
    "spec/models/invoice.rb",
    "spec/models/order.rb",
    "spec/models/post.rb",
    "spec/models/recipe.rb",
    "spec/models/record.rb",
    "spec/mongoid_auto_increment_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/proton/mongoid_auto_increment".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "2.6.14".freeze
  s.summary = "Auto-incrementing fields for Mongoid documents".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<mongoid>.freeze, [">= 2.0"])
      s.add_development_dependency(%q<bundler>.freeze, [">= 0"])
      s.add_development_dependency(%q<database_cleaner>.freeze, [">= 0.8.0"])
      s.add_development_dependency(%q<jeweler>.freeze, ["~> 2.1.1"])
      s.add_development_dependency(%q<rack>.freeze, ["~> 1.6.4"])
      s.add_development_dependency(%q<rake>.freeze, [">= 0"])
      s.add_development_dependency(%q<rdoc>.freeze, [">= 0"])
      s.add_development_dependency(%q<rspec>.freeze, [">= 2.0.0"])
      s.add_development_dependency(%q<simplecov>.freeze, [">= 0.4.0"])
    else
      s.add_dependency(%q<mongoid>.freeze, [">= 2.0"])
      s.add_dependency(%q<bundler>.freeze, [">= 0"])
      s.add_dependency(%q<database_cleaner>.freeze, [">= 0.8.0"])
      s.add_dependency(%q<jeweler>.freeze, ["~> 2.1.1"])
      s.add_dependency(%q<rack>.freeze, ["~> 1.6.4"])
      s.add_dependency(%q<rake>.freeze, [">= 0"])
      s.add_dependency(%q<rdoc>.freeze, [">= 0"])
      s.add_dependency(%q<rspec>.freeze, [">= 2.0.0"])
      s.add_dependency(%q<simplecov>.freeze, [">= 0.4.0"])
    end
  else
    s.add_dependency(%q<mongoid>.freeze, [">= 2.0"])
    s.add_dependency(%q<bundler>.freeze, [">= 0"])
    s.add_dependency(%q<database_cleaner>.freeze, [">= 0.8.0"])
    s.add_dependency(%q<jeweler>.freeze, ["~> 2.1.1"])
    s.add_dependency(%q<rack>.freeze, ["~> 1.6.4"])
    s.add_dependency(%q<rake>.freeze, [">= 0"])
    s.add_dependency(%q<rdoc>.freeze, [">= 0"])
    s.add_dependency(%q<rspec>.freeze, [">= 2.0.0"])
    s.add_dependency(%q<simplecov>.freeze, [">= 0.4.0"])
  end
end

